#!/bin/bash
#   Start/stop the timesync workaround process - Hristo
#       /etc/rc.d/init.d/
#
# chkconfig: 2345 13 87
#
#
#

# Source function library.
. /etc/init.d/functions
PATH=/usr/bin:/sbin:/bin:/usr/sbin
export PATH

RETVAL=0
prog="timesyncd"
executable="./usr/sbin/timesync"
own_pid=$$

start() {
    echo -n "Starting $prog: "
    daemon nohup $executable &> /dev/null &
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/timesyncd && success
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc timesyncd
    echo
    RETVAL=$?
    rm -f /var/lock/subsys/timesyncd
    return $RETVAL
}

check_running(){
    pid=`pidof -o $own_pid -x $prog`
    if [ $? -eq 0 ]; then
        echo "timesyncd is already running with pid: $pid"
	failure
	echo
        exit 1
    fi
}

case "$1" in
    start)
        check_running
        start
        ;;
    stop)
        stop
        ;;
    status)
        status timesyncd
	echo $?
        ;;
    restart)
        stop
        start
        ;;
    condrestart)
        if test "x`pidof timesync`" != x; then
        stop
        start
        fi
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|condrestart|status}"
        exit 1
esac

exit $RETVAL

